Branch cli
tidbcloud/tidbcloud-cli pull request #105
Opened 2023-06-06 10:31 UTC by shiyuhang0

## What is the purpose of the change

Add branch support
- create
- list
- describe
- delete
- connect-info
- connect (support connect to branch)

docs：https://github.com/pingcap/docs/pull/13880

## Brief change log

2023-06-21 06:46 UTC, xuanyu66 requested changes

2023-06-21 06:46 UTC, xuanyu66 commented on internal/cli/branch/connectinfo.go
> +var operatingSystemList = []string{
Reuse this list with cluster connectinfo.

2023-06-21 06:46 UTC, xuanyu66 commented on internal/cli/branch/connectinfo.go
> +		flag.BranchID,
BranchID or BranchName, which is better

2023-06-29 10:48 UTC, xuanyu66 requested changes

2023-06-30 07:51 UTC, xuanyu66 submitted a review, later dismissed

2023-06-30 09:07 UTC, zhangyangyu approved these changes

2023-06-30 09:13 UTC, merged